# Generated by Django 3.2.9 on 2021-12-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='OrderModel',
            name='number_of_products',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='OrderModel',
            name='title',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='OrderModel',
            name='totalPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='OrderModel',
            name='restaurant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
