# Generated by Django 3.2.9 on 2021-12-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20211218_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='OrderModel',
            name='number_of_products',
            field=models.FloatField(null=True),
        ),
    ]
