# Generated by Django 3.2.9 on 2021-12-18 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_OrderModel_number_of_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.RemoveField(
            model_name='OrderModel',
            name='title',
        ),
        migrations.AddField(
            model_name='OrderModel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
