# Generated by Django 3.2.9 on 2021-12-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20211218_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='OrderModel',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
