# Generated by Django 3.2.6 on 2022-01-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_create_at_zakazmodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
