# Generated by Django 3.2.9 on 2022-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20220109_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
